# Generated by Django 2.1.5 on 2019-02-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20190204_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteserverlog',
            name='quote_server_time',
            field=models.BigIntegerField(),
        ),
    ]
