# Generated by Django 2.1.5 on 2019-01-20 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_amount', models.PositiveIntegerField(default=0)),
                ('commited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_amount', models.PositiveIntegerField(default=0)),
                ('stock_sold_amount', models.PositiveIntegerField(default=0)),
                ('commited', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('sell_amount', models.PositiveIntegerField(default=0)),
                ('trigger_type', models.TextField(default='buy')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('password', models.CharField(max_length=50)),
                ('stocks', models.ManyToManyField(to='exchange.Stock')),
            ],
        ),
        migrations.AddField(
            model_name='trigger',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.User'),
        ),
        migrations.AddField(
            model_name='sell',
            name='stock_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Stock'),
        ),
        migrations.AddField(
            model_name='sell',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.User'),
        ),
        migrations.AddField(
            model_name='buy',
            name='stock_symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Stock'),
        ),
        migrations.AddField(
            model_name='buy',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.User'),
        ),
    ]
