# Generated by Django 2.1.5 on 2019-01-26 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('stock_symbol', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
            ],
        ),
        migrations.CreateModel(
            name='BuyTrigger',
            fields=[
                ('stock_symbol', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('committed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('stock_symbol', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('stock_sold_amount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SellTrigger',
            fields=[
                ('stock_symbol', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('stock_amount', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('committed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserStock',
            fields=[
                ('stock_symbol', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.User')),
            ],
        ),
        migrations.AddField(
            model_name='selltrigger',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.User'),
        ),
        migrations.AddField(
            model_name='sell',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.User'),
        ),
        migrations.AddField(
            model_name='buytrigger',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.User'),
        ),
        migrations.AddField(
            model_name='buy',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.User'),
        ),
    ]
