# Generated by Django 2.1.5 on 2019-01-31 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=64)),
                ('funds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BaseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('server', models.CharField(max_length=8)),
                ('transaction_num', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('stock_symbol', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('intended_cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('actual_cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('stock_bought_amount', models.PositiveIntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
            ],
        ),
        migrations.CreateModel(
            name='BuyTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=3)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('committed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DebugEventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=64)),
                ('stock_symbol', models.CharField(max_length=3)),
                ('filename', models.FilePathField(path='/dumplog_output')),
                ('funds', models.IntegerField(null=True)),
                ('debug_message', models.CharField(max_length=512)),
                ('base_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exchange.BaseLog')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorEventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=64)),
                ('stock_symbol', models.CharField(max_length=3)),
                ('filename', models.FilePathField(path='/dumplog_output')),
                ('funds', models.IntegerField(null=True)),
                ('error_message', models.CharField(max_length=512)),
                ('base_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exchange.BaseLog')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteServerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('stock_symbol', models.CharField(max_length=3)),
                ('username', models.CharField(max_length=128)),
                ('quote_server_time', models.PositiveIntegerField()),
                ('crypto_key', models.CharField(max_length=256)),
                ('base_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exchange.BaseLog')),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('stock_symbol', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('intended_cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('actual_cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('stock_sold_amount', models.PositiveIntegerField(default=0)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
            ],
        ),
        migrations.CreateModel(
            name='SellTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=3)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('stock_reserved_amount', models.PositiveIntegerField(default=0)),
                ('committed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SystemEventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=64)),
                ('stock_symbol', models.CharField(max_length=3)),
                ('filename', models.FilePathField(path='/dumplog_output')),
                ('funds', models.IntegerField(null=True)),
                ('base_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exchange.BaseLog')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserCommandLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=64)),
                ('stock_symbol', models.CharField(max_length=3)),
                ('filename', models.FilePathField(path='/dumplog_output')),
                ('funds', models.IntegerField(null=True)),
                ('base_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exchange.BaseLog')),
            ],
        ),
        migrations.CreateModel(
            name='UserStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=3)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.User')),
            ],
        ),
        migrations.AddField(
            model_name='selltrigger',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.User'),
        ),
        migrations.AddField(
            model_name='sell',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.User'),
        ),
        migrations.AddField(
            model_name='buytrigger',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.User'),
        ),
        migrations.AddField(
            model_name='buy',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.User'),
        ),
        migrations.AddField(
            model_name='accounttransactionlog',
            name='base_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exchange.BaseLog'),
        ),
    ]
