# Generated by Django 2.1.5 on 2019-01-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buytrigger',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selltrigger',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
