# Generated by Django 2.1.5 on 2019-02-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransactionlog',
            name='funds',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
        migrations.AlterField(
            model_name='debugeventlog',
            name='funds',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='erroreventlog',
            name='funds',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='quoteserverlog',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=32),
        ),
        migrations.AlterField(
            model_name='systemeventlog',
            name='funds',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='usercommandlog',
            name='funds',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True),
        ),
    ]
