# Generated by Django 2.1.5 on 2019-01-30 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20190127_2213'),
        ('exchange', '0003_selltrigger_stock_reserved_amount'),
    ]

    operations = [
    ]
