# Generated by Django 2.1.5 on 2019-01-31 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_merge_20190130_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=64)),
                ('funds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BaseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('server', models.CharField(max_length=8)),
                ('transaction_num', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DebugEventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=64)),
                ('stock_symbol', models.CharField(max_length=3)),
                ('filename', models.FilePathField(path='/dumplog_output')),
                ('funds', models.IntegerField(null=True)),
                ('debug_message', models.CharField(max_length=512)),
                ('base_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exchange.BaseLog')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorEventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=64)),
                ('stock_symbol', models.CharField(max_length=3)),
                ('filename', models.FilePathField(path='/dumplog_output')),
                ('funds', models.IntegerField(null=True)),
                ('error_message', models.CharField(max_length=512)),
                ('base_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exchange.BaseLog')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteServerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('stock_symbol', models.CharField(max_length=3)),
                ('username', models.CharField(max_length=128)),
                ('quote_server_time', models.PositiveIntegerField()),
                ('crypto_key', models.CharField(max_length=256)),
                ('base_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exchange.BaseLog')),
            ],
        ),
        migrations.CreateModel(
            name='SystemEventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=64)),
                ('stock_symbol', models.CharField(max_length=3)),
                ('filename', models.FilePathField(path='/dumplog_output')),
                ('funds', models.IntegerField(null=True)),
                ('base_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exchange.BaseLog')),
            ],
        ),
        migrations.CreateModel(
            name='UserCommandLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=16)),
                ('username', models.CharField(max_length=64)),
                ('stock_symbol', models.CharField(max_length=3)),
                ('filename', models.FilePathField(path='/dumplog_output')),
                ('funds', models.IntegerField(null=True)),
                ('base_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exchange.BaseLog')),
            ],
        ),
        migrations.AddField(
            model_name='accounttransactionlog',
            name='base_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exchange.BaseLog'),
        ),
    ]
