// Code generated by protoc-gen-go. DO NOT EDIT.
// source: daytrader.proto

package daytrader

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Command struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Amount               float32  `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Symbol               string   `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Filename             string   `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"`
	TransactionId        int32    `protobuf:"varint,6,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Name                 string   `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_59c1366fd5914009, []int{0}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Command) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Command) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Command) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Command) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *Command) GetTransactionId() int32 {
	if m != nil {
		return m.TransactionId
	}
	return 0
}

func (m *Command) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Log struct {
	Command              string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	ServerName           string   `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	TransactionNum       int32    `protobuf:"varint,3,opt,name=transaction_num,json=transactionNum,proto3" json:"transaction_num,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	StockSymbol          string   `protobuf:"bytes,5,opt,name=stock_symbol,json=stockSymbol,proto3" json:"stock_symbol,omitempty"`
	Price                float32  `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	Funds                float32  `protobuf:"fixed32,7,opt,name=funds,proto3" json:"funds,omitempty"`
	Filename             string   `protobuf:"bytes,8,opt,name=filename,proto3" json:"filename,omitempty"`
	CryptoKey            string   `protobuf:"bytes,9,opt,name=crypto_key,json=cryptoKey,proto3" json:"crypto_key,omitempty"`
	QuoteServerTime      int64    `protobuf:"varint,10,opt,name=quote_server_time,json=quoteServerTime,proto3" json:"quote_server_time,omitempty"`
	AccountAction        string   `protobuf:"bytes,11,opt,name=account_action,json=accountAction,proto3" json:"account_action,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,12,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	DebugMessage         string   `protobuf:"bytes,13,opt,name=debug_message,json=debugMessage,proto3" json:"debug_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_59c1366fd5914009, []int{1}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *Log) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *Log) GetTransactionNum() int32 {
	if m != nil {
		return m.TransactionNum
	}
	return 0
}

func (m *Log) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Log) GetStockSymbol() string {
	if m != nil {
		return m.StockSymbol
	}
	return ""
}

func (m *Log) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Log) GetFunds() float32 {
	if m != nil {
		return m.Funds
	}
	return 0
}

func (m *Log) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *Log) GetCryptoKey() string {
	if m != nil {
		return m.CryptoKey
	}
	return ""
}

func (m *Log) GetQuoteServerTime() int64 {
	if m != nil {
		return m.QuoteServerTime
	}
	return 0
}

func (m *Log) GetAccountAction() string {
	if m != nil {
		return m.AccountAction
	}
	return ""
}

func (m *Log) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *Log) GetDebugMessage() string {
	if m != nil {
		return m.DebugMessage
	}
	return ""
}

type UserResponse struct {
	UserId               string           `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance              float32          `protobuf:"fixed32,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Stocks               map[string]int32 `protobuf:"bytes,3,rep,name=stocks,proto3" json:"stocks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_59c1366fd5914009, []int{2}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserResponse) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *UserResponse) GetStocks() map[string]int32 {
	if m != nil {
		return m.Stocks
	}
	return nil
}

type BalanceResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance              float32  `protobuf:"fixed32,2,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceResponse) Reset()         { *m = BalanceResponse{} }
func (m *BalanceResponse) String() string { return proto.CompactTextString(m) }
func (*BalanceResponse) ProtoMessage()    {}
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_59c1366fd5914009, []int{3}
}

func (m *BalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceResponse.Unmarshal(m, b)
}
func (m *BalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceResponse.Marshal(b, m, deterministic)
}
func (m *BalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceResponse.Merge(m, src)
}
func (m *BalanceResponse) XXX_Size() int {
	return xxx_messageInfo_BalanceResponse.Size(m)
}
func (m *BalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceResponse proto.InternalMessageInfo

func (m *BalanceResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *BalanceResponse) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type StockUpdateResponse struct {
	UserId               string           `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Stocks               map[string]int32 `protobuf:"bytes,2,rep,name=stocks,proto3" json:"stocks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StockUpdateResponse) Reset()         { *m = StockUpdateResponse{} }
func (m *StockUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*StockUpdateResponse) ProtoMessage()    {}
func (*StockUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_59c1366fd5914009, []int{4}
}

func (m *StockUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockUpdateResponse.Unmarshal(m, b)
}
func (m *StockUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockUpdateResponse.Marshal(b, m, deterministic)
}
func (m *StockUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockUpdateResponse.Merge(m, src)
}
func (m *StockUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_StockUpdateResponse.Size(m)
}
func (m *StockUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StockUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StockUpdateResponse proto.InternalMessageInfo

func (m *StockUpdateResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *StockUpdateResponse) GetStocks() map[string]int32 {
	if m != nil {
		return m.Stocks
	}
	return nil
}

type PriceResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Price                float32  `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceResponse) Reset()         { *m = PriceResponse{} }
func (m *PriceResponse) String() string { return proto.CompactTextString(m) }
func (*PriceResponse) ProtoMessage()    {}
func (*PriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_59c1366fd5914009, []int{5}
}

func (m *PriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceResponse.Unmarshal(m, b)
}
func (m *PriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceResponse.Marshal(b, m, deterministic)
}
func (m *PriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceResponse.Merge(m, src)
}
func (m *PriceResponse) XXX_Size() int {
	return xxx_messageInfo_PriceResponse.Size(m)
}
func (m *PriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PriceResponse proto.InternalMessageInfo

func (m *PriceResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PriceResponse) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type Trigger struct {
	Price                float32  `protobuf:"fixed32,1,opt,name=price,proto3" json:"price,omitempty"`
	Amount               float32  `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Symbol               string   `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Buy                  bool     `protobuf:"varint,4,opt,name=buy,proto3" json:"buy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trigger) Reset()         { *m = Trigger{} }
func (m *Trigger) String() string { return proto.CompactTextString(m) }
func (*Trigger) ProtoMessage()    {}
func (*Trigger) Descriptor() ([]byte, []int) {
	return fileDescriptor_59c1366fd5914009, []int{6}
}

func (m *Trigger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trigger.Unmarshal(m, b)
}
func (m *Trigger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trigger.Marshal(b, m, deterministic)
}
func (m *Trigger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trigger.Merge(m, src)
}
func (m *Trigger) XXX_Size() int {
	return xxx_messageInfo_Trigger.Size(m)
}
func (m *Trigger) XXX_DiscardUnknown() {
	xxx_messageInfo_Trigger.DiscardUnknown(m)
}

var xxx_messageInfo_Trigger proto.InternalMessageInfo

func (m *Trigger) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Trigger) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Trigger) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Trigger) GetBuy() bool {
	if m != nil {
		return m.Buy
	}
	return false
}

type Transaction struct {
	CommandName          string   `protobuf:"bytes,1,opt,name=command_name,json=commandName,proto3" json:"command_name,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	StockSymbol          string   `protobuf:"bytes,3,opt,name=stock_symbol,json=stockSymbol,proto3" json:"stock_symbol,omitempty"`
	Timestamp            string   `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_59c1366fd5914009, []int{7}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetCommandName() string {
	if m != nil {
		return m.CommandName
	}
	return ""
}

func (m *Transaction) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Transaction) GetStockSymbol() string {
	if m != nil {
		return m.StockSymbol
	}
	return ""
}

func (m *Transaction) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type SummaryResponse struct {
	UserInfo             *UserResponse  `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	BuyTriggers          []*Trigger     `protobuf:"bytes,3,rep,name=buy_triggers,json=buyTriggers,proto3" json:"buy_triggers,omitempty"`
	SellTriggers         []*Trigger     `protobuf:"bytes,4,rep,name=sell_triggers,json=sellTriggers,proto3" json:"sell_triggers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SummaryResponse) Reset()         { *m = SummaryResponse{} }
func (m *SummaryResponse) String() string { return proto.CompactTextString(m) }
func (*SummaryResponse) ProtoMessage()    {}
func (*SummaryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_59c1366fd5914009, []int{8}
}

func (m *SummaryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummaryResponse.Unmarshal(m, b)
}
func (m *SummaryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummaryResponse.Marshal(b, m, deterministic)
}
func (m *SummaryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummaryResponse.Merge(m, src)
}
func (m *SummaryResponse) XXX_Size() int {
	return xxx_messageInfo_SummaryResponse.Size(m)
}
func (m *SummaryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SummaryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SummaryResponse proto.InternalMessageInfo

func (m *SummaryResponse) GetUserInfo() *UserResponse {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *SummaryResponse) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *SummaryResponse) GetBuyTriggers() []*Trigger {
	if m != nil {
		return m.BuyTriggers
	}
	return nil
}

func (m *SummaryResponse) GetSellTriggers() []*Trigger {
	if m != nil {
		return m.SellTriggers
	}
	return nil
}

type Response struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_59c1366fd5914009, []int{9}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Command)(nil), "daytrader.command")
	proto.RegisterType((*Log)(nil), "daytrader.log")
	proto.RegisterType((*UserResponse)(nil), "daytrader.UserResponse")
	proto.RegisterMapType((map[string]int32)(nil), "daytrader.UserResponse.StocksEntry")
	proto.RegisterType((*BalanceResponse)(nil), "daytrader.BalanceResponse")
	proto.RegisterType((*StockUpdateResponse)(nil), "daytrader.StockUpdateResponse")
	proto.RegisterMapType((map[string]int32)(nil), "daytrader.StockUpdateResponse.StocksEntry")
	proto.RegisterType((*PriceResponse)(nil), "daytrader.PriceResponse")
	proto.RegisterType((*Trigger)(nil), "daytrader.Trigger")
	proto.RegisterType((*Transaction)(nil), "daytrader.Transaction")
	proto.RegisterType((*SummaryResponse)(nil), "daytrader.SummaryResponse")
	proto.RegisterType((*Response)(nil), "daytrader.Response")
}

func init() { proto.RegisterFile("daytrader.proto", fileDescriptor_59c1366fd5914009) }

var fileDescriptor_59c1366fd5914009 = []byte{
	// 1012 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xae, 0xe3, 0xe6, 0xc7, 0x27, 0x7f, 0xcb, 0x14, 0x76, 0xad, 0x8a, 0x9f, 0xe0, 0x15, 0x22,
	0xda, 0x8b, 0x5e, 0x94, 0x5d, 0x76, 0xe9, 0xfe, 0x88, 0xa4, 0x29, 0xa8, 0x22, 0xac, 0xc0, 0xe9,
	0x5e, 0x47, 0x93, 0x78, 0x6a, 0x45, 0xb5, 0x3d, 0x61, 0x66, 0x5c, 0xe4, 0x47, 0xe0, 0x5d, 0xe0,
	0x01, 0x78, 0x00, 0x9e, 0x84, 0x07, 0xe0, 0x82, 0x17, 0x40, 0x33, 0x63, 0x3b, 0x4e, 0x89, 0xdb,
	0xb4, 0x45, 0xdc, 0xf9, 0x9c, 0x99, 0xef, 0x9c, 0xf3, 0x9d, 0x39, 0xe7, 0x8b, 0x02, 0x5d, 0x0f,
	0x27, 0x82, 0x61, 0x8f, 0xb0, 0x83, 0x25, 0xa3, 0x82, 0x22, 0x2b, 0x77, 0x38, 0x7f, 0x18, 0x50,
	0x9f, 0xd3, 0x30, 0xc4, 0x91, 0x87, 0x1e, 0x41, 0x3d, 0xe6, 0x84, 0x4d, 0x17, 0x9e, 0x6d, 0xf4,
	0x8c, 0xbe, 0xe5, 0xd6, 0xa4, 0x79, 0xea, 0xa1, 0x7d, 0x68, 0x2c, 0x31, 0xe7, 0x3f, 0x53, 0xe6,
	0xd9, 0x15, 0x75, 0x92, 0xdb, 0xe8, 0x21, 0xd4, 0x70, 0x48, 0xe3, 0x48, 0xd8, 0x66, 0xcf, 0xe8,
	0x57, 0xdc, 0xd4, 0x92, 0x7e, 0x9e, 0x84, 0x33, 0x1a, 0xd8, 0xbb, 0x3a, 0x96, 0xb6, 0x64, 0xac,
	0xf3, 0x45, 0x40, 0x22, 0x1c, 0x12, 0xbb, 0xaa, 0x63, 0x65, 0x36, 0xfa, 0x0c, 0x3a, 0x82, 0xe1,
	0x88, 0xe3, 0xb9, 0x58, 0xd0, 0x48, 0xd6, 0x51, 0xeb, 0x19, 0xfd, 0xaa, 0xdb, 0x2e, 0x78, 0x4f,
	0x3d, 0x84, 0x60, 0x57, 0xc1, 0xeb, 0x0a, 0xae, 0xbe, 0x9d, 0x5f, 0x4d, 0x30, 0x03, 0xea, 0x23,
	0x3b, 0xa7, 0x93, 0x72, 0xc8, 0xd9, 0x7d, 0x02, 0x4d, 0x4e, 0xd8, 0x25, 0x61, 0x53, 0x05, 0xd6,
	0x3c, 0x40, 0xbb, 0xde, 0xca, 0xec, 0x9f, 0x43, 0xb7, 0x98, 0x3d, 0x8a, 0x43, 0x45, 0xa9, 0xea,
	0x16, 0x8b, 0x7a, 0x1b, 0x87, 0x92, 0x82, 0x6c, 0x8c, 0x0a, 0xa3, 0xc9, 0xe5, 0x36, 0xfa, 0x14,
	0x5a, 0x5c, 0xd0, 0xf9, 0xc5, 0x34, 0x25, 0xaf, 0x29, 0x36, 0x95, 0x6f, 0xa2, 0x3b, 0xf0, 0x3e,
	0x54, 0x97, 0x6c, 0x31, 0x27, 0x8a, 0x5c, 0xc5, 0xd5, 0x86, 0xf4, 0x9e, 0xc7, 0x91, 0xc7, 0x15,
	0xab, 0x8a, 0xab, 0x8d, 0xb5, 0x6e, 0x35, 0xae, 0x74, 0xeb, 0x23, 0x80, 0x39, 0x4b, 0x96, 0x82,
	0x4e, 0x2f, 0x48, 0x62, 0x5b, 0xea, 0xd4, 0xd2, 0x9e, 0xef, 0x48, 0x82, 0x9e, 0xc0, 0x7b, 0x3f,
	0xc5, 0x54, 0x90, 0x69, 0xca, 0x5a, 0x2c, 0x42, 0x62, 0x43, 0xcf, 0xe8, 0x9b, 0x6e, 0x57, 0x1d,
	0x4c, 0x94, 0xff, 0x6c, 0xa1, 0x1b, 0x8f, 0xe7, 0x73, 0xf9, 0x6e, 0x53, 0x4d, 0xd3, 0x6e, 0xaa,
	0x70, 0xed, 0xd4, 0x3b, 0x50, 0x4e, 0xf4, 0x18, 0xda, 0x84, 0x31, 0xca, 0xa6, 0x21, 0xe1, 0x1c,
	0xfb, 0xc4, 0x6e, 0xa9, 0x5b, 0x2d, 0xe5, 0xfc, 0x5e, 0xfb, 0xe4, 0x25, 0x8f, 0xcc, 0x62, 0x3f,
	0xbf, 0xd4, 0xd6, 0x97, 0x94, 0x33, 0xbd, 0xe4, 0xfc, 0x6e, 0x40, 0xeb, 0x1d, 0x27, 0xcc, 0x25,
	0x7c, 0x49, 0x23, 0x4e, 0xca, 0x67, 0xcf, 0x86, 0xfa, 0x0c, 0x07, 0x38, 0x9a, 0xeb, 0x27, 0xab,
	0xb8, 0x99, 0x89, 0x5e, 0x42, 0x4d, 0xb5, 0x95, 0xdb, 0x66, 0xcf, 0xec, 0x37, 0x0f, 0x1f, 0x1f,
	0xac, 0xe6, 0xbc, 0x18, 0xfb, 0x60, 0xa2, 0x6e, 0x9d, 0x44, 0x82, 0x25, 0x6e, 0x0a, 0xd9, 0xff,
	0x0a, 0x9a, 0x05, 0x37, 0x7a, 0x00, 0xa6, 0x6c, 0xa2, 0x4e, 0x2d, 0x3f, 0xe5, 0x7b, 0x5c, 0xe2,
	0x20, 0xd6, 0x59, 0xab, 0xae, 0x36, 0x8e, 0x2a, 0x2f, 0x0c, 0x67, 0x04, 0xdd, 0xa1, 0x2e, 0xe1,
	0x1e, 0xd5, 0x3b, 0xbf, 0x19, 0xb0, 0xa7, 0x2a, 0x78, 0xb7, 0xf4, 0xb0, 0xd8, 0x22, 0xd4, 0x30,
	0xa7, 0x5b, 0x51, 0x74, 0x9f, 0x14, 0xe8, 0x6e, 0x08, 0xf4, 0x5f, 0xb3, 0x7e, 0x03, 0xed, 0x1f,
	0xe4, 0xa0, 0xde, 0x5c, 0x68, 0x3e, 0xdf, 0x95, 0xc2, 0x7c, 0x3b, 0x18, 0xea, 0x67, 0x6c, 0xe1,
	0xfb, 0x84, 0xad, 0x2e, 0x18, 0xc5, 0x05, 0x58, 0x09, 0x49, 0xa5, 0x44, 0x48, 0xcc, 0x35, 0x21,
	0x79, 0x00, 0xe6, 0x2c, 0x4e, 0xd4, 0x02, 0x36, 0x5c, 0xf9, 0xe9, 0xfc, 0x62, 0x40, 0xf3, 0x6c,
	0xb5, 0xaa, 0x72, 0x17, 0xd3, 0xe5, 0xd7, 0x2b, 0xaf, 0xcb, 0x6c, 0xa6, 0x3e, 0xb5, 0xf3, 0xeb,
	0x49, 0xad, 0x3c, 0xe9, 0xd5, 0x35, 0x36, 0xff, 0xbd, 0xc6, 0x1f, 0x82, 0x25, 0x57, 0x8a, 0x0b,
	0x1c, 0x2e, 0x53, 0x19, 0x58, 0x39, 0x9c, 0xbf, 0x0d, 0xe8, 0x4e, 0xe2, 0x30, 0xc4, 0x2c, 0xc9,
	0x3b, 0xf6, 0x14, 0x2c, 0xdd, 0xb1, 0xe8, 0x9c, 0xaa, 0x62, 0x9a, 0x87, 0x8f, 0x4a, 0x66, 0x56,
	0x2b, 0xca, 0x69, 0x74, 0x4e, 0xd1, 0x11, 0xb4, 0x0a, 0xfa, 0x93, 0xbd, 0xfe, 0xc3, 0x02, 0xb0,
	0xc0, 0xd9, 0x5d, 0xbb, 0x8b, 0x9e, 0x41, 0x6b, 0x16, 0x27, 0x53, 0xa1, 0x1b, 0x9f, 0x2d, 0x0a,
	0x5a, 0xc3, 0xaa, 0x23, 0xb7, 0x39, 0x8b, 0x93, 0xf4, 0x9b, 0xa3, 0xe7, 0xd0, 0xe6, 0x24, 0x08,
	0x56, 0xb8, 0xdd, 0x52, 0x5c, 0x4b, 0x5e, 0xcc, 0x80, 0xce, 0x6b, 0x68, 0x6c, 0xb5, 0x13, 0x99,
	0x34, 0xe8, 0xa6, 0x67, 0xe6, 0xe1, 0x9f, 0x26, 0xd4, 0xc6, 0x54, 0xcd, 0xc8, 0x73, 0xe8, 0x8c,
	0xa9, 0x2f, 0x5b, 0x72, 0x9c, 0xea, 0x77, 0xa7, 0x90, 0x3d, 0xa0, 0xfe, 0xfe, 0x5e, 0xc1, 0xce,
	0x92, 0x3a, 0x3b, 0xe8, 0x15, 0xec, 0x8d, 0xa9, 0xff, 0xe3, 0x4a, 0xe0, 0x4e, 0x2e, 0x49, 0x24,
	0xb6, 0x45, 0xbf, 0x81, 0x0f, 0xc6, 0xd4, 0x1f, 0x68, 0xd5, 0x2b, 0xce, 0xd2, 0x96, 0x78, 0x5d,
	0xf6, 0x24, 0xe1, 0x82, 0x84, 0xb7, 0x4a, 0xfc, 0x25, 0xb4, 0xc7, 0xd4, 0x3f, 0x91, 0x42, 0x7a,
	0x07, 0xdc, 0x48, 0x6a, 0xeb, 0xad, 0x70, 0xcf, 0xa0, 0x31, 0x8a, 0xc3, 0xe5, 0x98, 0xfa, 0x1c,
	0x15, 0xdf, 0x35, 0x5d, 0x8e, 0x32, 0xd8, 0x10, 0x3a, 0xa3, 0x05, 0x5f, 0x06, 0x38, 0x49, 0x87,
	0x7b, 0x23, 0x78, 0xbf, 0x28, 0x4d, 0xeb, 0x4b, 0xe0, 0xec, 0x1c, 0xfe, 0xd5, 0x00, 0x6b, 0x84,
	0x93, 0x33, 0x75, 0x8e, 0x5e, 0x40, 0xfd, 0x5b, 0x22, 0xe4, 0x43, 0x6f, 0x0c, 0x55, 0xb6, 0x20,
	0xaa, 0xd7, 0x70, 0xcc, 0x08, 0x16, 0xa4, 0x14, 0x5c, 0xfa, 0x48, 0xe6, 0xc0, 0xf3, 0x6e, 0xac,
	0xfc, 0x8a, 0xc8, 0x2b, 0x60, 0x55, 0x0d, 0xd6, 0x46, 0xa8, 0x5d, 0xf0, 0xad, 0x29, 0xa5, 0xce,
	0x38, 0x8c, 0x93, 0x3b, 0x64, 0x7c, 0x05, 0xbb, 0x13, 0x12, 0x04, 0x1b, 0x91, 0x1f, 0x5f, 0xff,
	0x03, 0xe0, 0xec, 0xa0, 0x01, 0x58, 0x72, 0x7b, 0x16, 0xa2, 0x2c, 0xf9, 0xcd, 0x21, 0x5e, 0x02,
	0xe8, 0x10, 0xa5, 0x65, 0x5c, 0xf3, 0x42, 0xaf, 0xc1, 0x3a, 0x96, 0x84, 0x82, 0xbb, 0x91, 0x1f,
	0x02, 0x68, 0xf8, 0x3d, 0x5a, 0xf0, 0x35, 0xb4, 0x26, 0x44, 0xf2, 0x1f, 0x68, 0x61, 0xbf, 0x7d,
	0x15, 0x47, 0xd0, 0x9e, 0x10, 0x45, 0xff, 0x9a, 0x10, 0x25, 0x93, 0xa6, 0xb1, 0xc3, 0x5c, 0x5a,
	0x6f, 0x83, 0xfd, 0x06, 0x3a, 0x69, 0xde, 0xeb, 0xc0, 0x5b, 0x75, 0x20, 0xeb, 0xa2, 0xb8, 0xdb,
	0x3b, 0x9c, 0x40, 0x3b, 0x8f, 0x70, 0x8f, 0xa7, 0x78, 0x0a, 0xf5, 0x54, 0x72, 0xfe, 0x67, 0xc5,
	0x99, 0xd5, 0xd4, 0xdf, 0x9e, 0x2f, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x64, 0x26, 0x7d,
	0x09, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoggerClient is the client API for Logger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoggerClient interface {
	LogUserCommand(ctx context.Context, in *Log, opts ...grpc.CallOption) (*Response, error)
	LogQuoteServerEvent(ctx context.Context, in *Log, opts ...grpc.CallOption) (*Response, error)
	LogAccountTransaction(ctx context.Context, in *Log, opts ...grpc.CallOption) (*Response, error)
	LogSystemEvent(ctx context.Context, in *Log, opts ...grpc.CallOption) (*Response, error)
	LogErrorEvent(ctx context.Context, in *Log, opts ...grpc.CallOption) (*Response, error)
	LogDebugEvent(ctx context.Context, in *Log, opts ...grpc.CallOption) (*Response, error)
	DumpLogs(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	DisplaySummary(ctx context.Context, in *Command, opts ...grpc.CallOption) (*SummaryResponse, error)
}

type loggerClient struct {
	cc *grpc.ClientConn
}

func NewLoggerClient(cc *grpc.ClientConn) LoggerClient {
	return &loggerClient{cc}
}

func (c *loggerClient) LogUserCommand(ctx context.Context, in *Log, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/daytrader.Logger/LogUserCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) LogQuoteServerEvent(ctx context.Context, in *Log, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/daytrader.Logger/LogQuoteServerEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) LogAccountTransaction(ctx context.Context, in *Log, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/daytrader.Logger/LogAccountTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) LogSystemEvent(ctx context.Context, in *Log, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/daytrader.Logger/LogSystemEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) LogErrorEvent(ctx context.Context, in *Log, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/daytrader.Logger/LogErrorEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) LogDebugEvent(ctx context.Context, in *Log, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/daytrader.Logger/LogDebugEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) DumpLogs(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/daytrader.Logger/DumpLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) DisplaySummary(ctx context.Context, in *Command, opts ...grpc.CallOption) (*SummaryResponse, error) {
	out := new(SummaryResponse)
	err := c.cc.Invoke(ctx, "/daytrader.Logger/DisplaySummary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggerServer is the server API for Logger service.
type LoggerServer interface {
	LogUserCommand(context.Context, *Log) (*Response, error)
	LogQuoteServerEvent(context.Context, *Log) (*Response, error)
	LogAccountTransaction(context.Context, *Log) (*Response, error)
	LogSystemEvent(context.Context, *Log) (*Response, error)
	LogErrorEvent(context.Context, *Log) (*Response, error)
	LogDebugEvent(context.Context, *Log) (*Response, error)
	DumpLogs(context.Context, *Command) (*Response, error)
	DisplaySummary(context.Context, *Command) (*SummaryResponse, error)
}

func RegisterLoggerServer(s *grpc.Server, srv LoggerServer) {
	s.RegisterService(&_Logger_serviceDesc, srv)
}

func _Logger_LogUserCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Log)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).LogUserCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.Logger/LogUserCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).LogUserCommand(ctx, req.(*Log))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logger_LogQuoteServerEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Log)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).LogQuoteServerEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.Logger/LogQuoteServerEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).LogQuoteServerEvent(ctx, req.(*Log))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logger_LogAccountTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Log)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).LogAccountTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.Logger/LogAccountTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).LogAccountTransaction(ctx, req.(*Log))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logger_LogSystemEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Log)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).LogSystemEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.Logger/LogSystemEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).LogSystemEvent(ctx, req.(*Log))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logger_LogErrorEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Log)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).LogErrorEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.Logger/LogErrorEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).LogErrorEvent(ctx, req.(*Log))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logger_LogDebugEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Log)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).LogDebugEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.Logger/LogDebugEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).LogDebugEvent(ctx, req.(*Log))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logger_DumpLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).DumpLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.Logger/DumpLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).DumpLogs(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logger_DisplaySummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).DisplaySummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.Logger/DisplaySummary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).DisplaySummary(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

var _Logger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "daytrader.Logger",
	HandlerType: (*LoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LogUserCommand",
			Handler:    _Logger_LogUserCommand_Handler,
		},
		{
			MethodName: "LogQuoteServerEvent",
			Handler:    _Logger_LogQuoteServerEvent_Handler,
		},
		{
			MethodName: "LogAccountTransaction",
			Handler:    _Logger_LogAccountTransaction_Handler,
		},
		{
			MethodName: "LogSystemEvent",
			Handler:    _Logger_LogSystemEvent_Handler,
		},
		{
			MethodName: "LogErrorEvent",
			Handler:    _Logger_LogErrorEvent_Handler,
		},
		{
			MethodName: "LogDebugEvent",
			Handler:    _Logger_LogDebugEvent_Handler,
		},
		{
			MethodName: "DumpLogs",
			Handler:    _Logger_DumpLogs_Handler,
		},
		{
			MethodName: "DisplaySummary",
			Handler:    _Logger_DisplaySummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "daytrader.proto",
}

// DayTraderClient is the client API for DayTrader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DayTraderClient interface {
	GetUser(ctx context.Context, in *Command, opts ...grpc.CallOption) (*UserResponse, error)
	CreateUser(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	Add(ctx context.Context, in *Command, opts ...grpc.CallOption) (*BalanceResponse, error)
	Quote(ctx context.Context, in *Command, opts ...grpc.CallOption) (*PriceResponse, error)
	Buy(ctx context.Context, in *Command, opts ...grpc.CallOption) (*BalanceResponse, error)
	Sell(ctx context.Context, in *Command, opts ...grpc.CallOption) (*StockUpdateResponse, error)
	CommitBuy(ctx context.Context, in *Command, opts ...grpc.CallOption) (*StockUpdateResponse, error)
	CommitSell(ctx context.Context, in *Command, opts ...grpc.CallOption) (*UserResponse, error)
	CancelBuy(ctx context.Context, in *Command, opts ...grpc.CallOption) (*BalanceResponse, error)
	CancelSell(ctx context.Context, in *Command, opts ...grpc.CallOption) (*StockUpdateResponse, error)
	SetBuyAmount(ctx context.Context, in *Command, opts ...grpc.CallOption) (*BalanceResponse, error)
	SetSellAmount(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	SetBuyTrigger(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	SetSellTrigger(ctx context.Context, in *Command, opts ...grpc.CallOption) (*StockUpdateResponse, error)
	CancelSetBuy(ctx context.Context, in *Command, opts ...grpc.CallOption) (*BalanceResponse, error)
	CancelSetSell(ctx context.Context, in *Command, opts ...grpc.CallOption) (*StockUpdateResponse, error)
	DumpLog(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	DisplaySummary(ctx context.Context, in *Command, opts ...grpc.CallOption) (*SummaryResponse, error)
}

type dayTraderClient struct {
	cc *grpc.ClientConn
}

func NewDayTraderClient(cc *grpc.ClientConn) DayTraderClient {
	return &dayTraderClient{cc}
}

func (c *dayTraderClient) GetUser(ctx context.Context, in *Command, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/daytrader.DayTrader/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) CreateUser(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/daytrader.DayTrader/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) Add(ctx context.Context, in *Command, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, "/daytrader.DayTrader/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) Quote(ctx context.Context, in *Command, opts ...grpc.CallOption) (*PriceResponse, error) {
	out := new(PriceResponse)
	err := c.cc.Invoke(ctx, "/daytrader.DayTrader/Quote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) Buy(ctx context.Context, in *Command, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, "/daytrader.DayTrader/Buy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) Sell(ctx context.Context, in *Command, opts ...grpc.CallOption) (*StockUpdateResponse, error) {
	out := new(StockUpdateResponse)
	err := c.cc.Invoke(ctx, "/daytrader.DayTrader/Sell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) CommitBuy(ctx context.Context, in *Command, opts ...grpc.CallOption) (*StockUpdateResponse, error) {
	out := new(StockUpdateResponse)
	err := c.cc.Invoke(ctx, "/daytrader.DayTrader/CommitBuy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) CommitSell(ctx context.Context, in *Command, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/daytrader.DayTrader/CommitSell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) CancelBuy(ctx context.Context, in *Command, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, "/daytrader.DayTrader/CancelBuy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) CancelSell(ctx context.Context, in *Command, opts ...grpc.CallOption) (*StockUpdateResponse, error) {
	out := new(StockUpdateResponse)
	err := c.cc.Invoke(ctx, "/daytrader.DayTrader/CancelSell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) SetBuyAmount(ctx context.Context, in *Command, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, "/daytrader.DayTrader/SetBuyAmount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) SetSellAmount(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/daytrader.DayTrader/SetSellAmount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) SetBuyTrigger(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/daytrader.DayTrader/SetBuyTrigger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) SetSellTrigger(ctx context.Context, in *Command, opts ...grpc.CallOption) (*StockUpdateResponse, error) {
	out := new(StockUpdateResponse)
	err := c.cc.Invoke(ctx, "/daytrader.DayTrader/SetSellTrigger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) CancelSetBuy(ctx context.Context, in *Command, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, "/daytrader.DayTrader/CancelSetBuy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) CancelSetSell(ctx context.Context, in *Command, opts ...grpc.CallOption) (*StockUpdateResponse, error) {
	out := new(StockUpdateResponse)
	err := c.cc.Invoke(ctx, "/daytrader.DayTrader/CancelSetSell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) DumpLog(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/daytrader.DayTrader/DumpLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) DisplaySummary(ctx context.Context, in *Command, opts ...grpc.CallOption) (*SummaryResponse, error) {
	out := new(SummaryResponse)
	err := c.cc.Invoke(ctx, "/daytrader.DayTrader/DisplaySummary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DayTraderServer is the server API for DayTrader service.
type DayTraderServer interface {
	GetUser(context.Context, *Command) (*UserResponse, error)
	CreateUser(context.Context, *Command) (*Response, error)
	Add(context.Context, *Command) (*BalanceResponse, error)
	Quote(context.Context, *Command) (*PriceResponse, error)
	Buy(context.Context, *Command) (*BalanceResponse, error)
	Sell(context.Context, *Command) (*StockUpdateResponse, error)
	CommitBuy(context.Context, *Command) (*StockUpdateResponse, error)
	CommitSell(context.Context, *Command) (*UserResponse, error)
	CancelBuy(context.Context, *Command) (*BalanceResponse, error)
	CancelSell(context.Context, *Command) (*StockUpdateResponse, error)
	SetBuyAmount(context.Context, *Command) (*BalanceResponse, error)
	SetSellAmount(context.Context, *Command) (*Response, error)
	SetBuyTrigger(context.Context, *Command) (*Response, error)
	SetSellTrigger(context.Context, *Command) (*StockUpdateResponse, error)
	CancelSetBuy(context.Context, *Command) (*BalanceResponse, error)
	CancelSetSell(context.Context, *Command) (*StockUpdateResponse, error)
	DumpLog(context.Context, *Command) (*Response, error)
	DisplaySummary(context.Context, *Command) (*SummaryResponse, error)
}

func RegisterDayTraderServer(s *grpc.Server, srv DayTraderServer) {
	s.RegisterService(&_DayTrader_serviceDesc, srv)
}

func _DayTrader_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.DayTrader/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).GetUser(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.DayTrader/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).CreateUser(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.DayTrader/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).Add(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_Quote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).Quote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.DayTrader/Quote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).Quote(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_Buy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).Buy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.DayTrader/Buy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).Buy(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_Sell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).Sell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.DayTrader/Sell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).Sell(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_CommitBuy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).CommitBuy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.DayTrader/CommitBuy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).CommitBuy(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_CommitSell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).CommitSell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.DayTrader/CommitSell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).CommitSell(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_CancelBuy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).CancelBuy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.DayTrader/CancelBuy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).CancelBuy(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_CancelSell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).CancelSell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.DayTrader/CancelSell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).CancelSell(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_SetBuyAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).SetBuyAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.DayTrader/SetBuyAmount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).SetBuyAmount(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_SetSellAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).SetSellAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.DayTrader/SetSellAmount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).SetSellAmount(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_SetBuyTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).SetBuyTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.DayTrader/SetBuyTrigger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).SetBuyTrigger(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_SetSellTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).SetSellTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.DayTrader/SetSellTrigger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).SetSellTrigger(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_CancelSetBuy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).CancelSetBuy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.DayTrader/CancelSetBuy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).CancelSetBuy(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_CancelSetSell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).CancelSetSell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.DayTrader/CancelSetSell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).CancelSetSell(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_DumpLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).DumpLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.DayTrader/DumpLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).DumpLog(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_DisplaySummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).DisplaySummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daytrader.DayTrader/DisplaySummary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).DisplaySummary(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

var _DayTrader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "daytrader.DayTrader",
	HandlerType: (*DayTraderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _DayTrader_GetUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _DayTrader_CreateUser_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _DayTrader_Add_Handler,
		},
		{
			MethodName: "Quote",
			Handler:    _DayTrader_Quote_Handler,
		},
		{
			MethodName: "Buy",
			Handler:    _DayTrader_Buy_Handler,
		},
		{
			MethodName: "Sell",
			Handler:    _DayTrader_Sell_Handler,
		},
		{
			MethodName: "CommitBuy",
			Handler:    _DayTrader_CommitBuy_Handler,
		},
		{
			MethodName: "CommitSell",
			Handler:    _DayTrader_CommitSell_Handler,
		},
		{
			MethodName: "CancelBuy",
			Handler:    _DayTrader_CancelBuy_Handler,
		},
		{
			MethodName: "CancelSell",
			Handler:    _DayTrader_CancelSell_Handler,
		},
		{
			MethodName: "SetBuyAmount",
			Handler:    _DayTrader_SetBuyAmount_Handler,
		},
		{
			MethodName: "SetSellAmount",
			Handler:    _DayTrader_SetSellAmount_Handler,
		},
		{
			MethodName: "SetBuyTrigger",
			Handler:    _DayTrader_SetBuyTrigger_Handler,
		},
		{
			MethodName: "SetSellTrigger",
			Handler:    _DayTrader_SetSellTrigger_Handler,
		},
		{
			MethodName: "CancelSetBuy",
			Handler:    _DayTrader_CancelSetBuy_Handler,
		},
		{
			MethodName: "CancelSetSell",
			Handler:    _DayTrader_CancelSetSell_Handler,
		},
		{
			MethodName: "DumpLog",
			Handler:    _DayTrader_DumpLog_Handler,
		},
		{
			MethodName: "DisplaySummary",
			Handler:    _DayTrader_DisplaySummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "daytrader.proto",
}
