// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package server

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Command struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount               float32  `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Symbol               string   `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Filename             string   `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	TransactionId        int32    `protobuf:"varint,5,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Command) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Command) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Command) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *Command) GetTransactionId() int32 {
	if m != nil {
		return m.TransactionId
	}
	return 0
}

func (m *Command) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Command)(nil), "server.command")
	proto.RegisterType((*Response)(nil), "server.Response")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7) }

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xcd, 0x6a, 0xfa, 0x40,
	0x14, 0xc5, 0xff, 0xf1, 0x23, 0xd1, 0x8b, 0xfa, 0x2f, 0xb3, 0x68, 0x83, 0x2b, 0x91, 0x16, 0xc4,
	0x16, 0x69, 0xab, 0x7d, 0x00, 0xad, 0x1b, 0xa1, 0x9b, 0x26, 0xee, 0xcb, 0x68, 0x6e, 0x43, 0x20,
	0x93, 0x09, 0xf3, 0x51, 0xc8, 0x23, 0x75, 0xdb, 0x27, 0x2c, 0x99, 0x24, 0xd2, 0xe5, 0x64, 0x97,
	0x73, 0x73, 0x7e, 0x73, 0x72, 0x2e, 0x61, 0x60, 0x24, 0x51, 0x7c, 0xa1, 0x58, 0xe5, 0x82, 0x2b,
	0x4e, 0xdc, 0x4a, 0xcd, 0xbf, 0x1d, 0xf0, 0xce, 0x9c, 0x31, 0x9a, 0x45, 0xe4, 0x06, 0x3c, 0x2d,
	0x51, 0x7c, 0x24, 0x91, 0xef, 0xcc, 0x9c, 0xc5, 0x30, 0x70, 0x4b, 0x79, 0x88, 0xc8, 0x35, 0xb8,
	0x94, 0x71, 0x9d, 0x29, 0xbf, 0x33, 0x73, 0x16, 0x9d, 0xa0, 0x56, 0xe5, 0x5c, 0x16, 0xec, 0xc4,
	0x53, 0xbf, 0x5b, 0xf9, 0x2b, 0x45, 0xa6, 0x30, 0xf8, 0x4c, 0x52, 0xcc, 0x28, 0x43, 0xbf, 0x67,
	0xde, 0x5c, 0x34, 0xb9, 0x83, 0x89, 0x12, 0x34, 0x93, 0xf4, 0xac, 0x12, 0x9e, 0x95, 0x59, 0xfd,
	0x99, 0xb3, 0xe8, 0x07, 0xe3, 0x3f, 0xd3, 0x43, 0x44, 0x08, 0xf4, 0x0c, 0xee, 0x1a, 0xdc, 0x3c,
	0xcf, 0x6f, 0x61, 0x10, 0xa0, 0xcc, 0x79, 0x26, 0x91, 0xf8, 0xe0, 0x31, 0x94, 0x92, 0xc6, 0x58,
	0x7f, 0x6b, 0x23, 0x9f, 0x7f, 0x5c, 0x18, 0xee, 0x69, 0x71, 0x14, 0x34, 0x42, 0x41, 0x96, 0xd0,
	0xdd, 0x46, 0x11, 0xf9, 0xbf, 0xaa, 0xdb, 0xd7, 0x5d, 0xa7, 0x57, 0xcd, 0xa0, 0x39, 0x71, 0xfe,
	0x8f, 0x3c, 0x40, 0xff, 0x5d, 0x73, 0x85, 0x76, 0xee, 0x25, 0x74, 0x77, 0xba, 0xb0, 0xf3, 0xde,
	0x43, 0x2f, 0xc4, 0x34, 0xb5, 0x33, 0x3f, 0xc2, 0xf0, 0x95, 0x33, 0x96, 0x28, 0xeb, 0xe3, 0x9f,
	0x00, 0x2a, 0xa2, 0x5d, 0x08, 0xcd, 0xce, 0x98, 0xb6, 0x0a, 0x31, 0x84, 0x7d, 0xc8, 0x1a, 0x46,
	0x21, 0x96, 0x35, 0xb6, 0xd5, 0xff, 0x62, 0x05, 0x6d, 0x60, 0x1c, 0xa2, 0x69, 0xd2, 0x9e, 0xda,
	0xe9, 0xe2, 0x28, 0x92, 0x38, 0x46, 0x61, 0x47, 0xbd, 0xc0, 0xa4, 0xce, 0x6a, 0x85, 0x6d, 0x60,
	0xdc, 0xac, 0x42, 0xb5, 0xda, 0xc6, 0x85, 0xb2, 0xde, 0xfa, 0x0a, 0xbc, 0xbd, 0x66, 0xf9, 0x1b,
	0x8f, 0xad, 0x1b, 0xed, 0x13, 0x99, 0xa7, 0xb4, 0x08, 0x35, 0x63, 0x54, 0xd8, 0xc5, 0x9c, 0x5c,
	0x73, 0x2b, 0xac, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xf0, 0xa5, 0x96, 0x80, 0x25, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DayTraderClient is the client API for DayTrader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DayTraderClient interface {
	Add(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	Quote(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	Buy(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	Sell(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	CommitBuy(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	CommitSell(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	CancelBuy(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	CancelSell(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	SetBuyAmount(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	SetSellAmount(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	SetBuyTrigger(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	SetSellTrigger(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	CancelSetSell(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	CancelSetBuy(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	DumpLog(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
	DisplaySummary(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error)
}

type dayTraderClient struct {
	cc *grpc.ClientConn
}

func NewDayTraderClient(cc *grpc.ClientConn) DayTraderClient {
	return &dayTraderClient{cc}
}

func (c *dayTraderClient) Add(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/server.DayTrader/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) Quote(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/server.DayTrader/Quote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) Buy(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/server.DayTrader/Buy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) Sell(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/server.DayTrader/Sell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) CommitBuy(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/server.DayTrader/CommitBuy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) CommitSell(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/server.DayTrader/CommitSell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) CancelBuy(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/server.DayTrader/CancelBuy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) CancelSell(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/server.DayTrader/CancelSell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) SetBuyAmount(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/server.DayTrader/SetBuyAmount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) SetSellAmount(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/server.DayTrader/SetSellAmount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) SetBuyTrigger(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/server.DayTrader/SetBuyTrigger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) SetSellTrigger(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/server.DayTrader/SetSellTrigger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) CancelSetSell(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/server.DayTrader/CancelSetSell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) CancelSetBuy(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/server.DayTrader/CancelSetBuy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) DumpLog(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/server.DayTrader/DumpLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dayTraderClient) DisplaySummary(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/server.DayTrader/DisplaySummary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DayTraderServer is the server API for DayTrader service.
type DayTraderServer interface {
	Add(context.Context, *Command) (*Response, error)
	Quote(context.Context, *Command) (*Response, error)
	Buy(context.Context, *Command) (*Response, error)
	Sell(context.Context, *Command) (*Response, error)
	CommitBuy(context.Context, *Command) (*Response, error)
	CommitSell(context.Context, *Command) (*Response, error)
	CancelBuy(context.Context, *Command) (*Response, error)
	CancelSell(context.Context, *Command) (*Response, error)
	SetBuyAmount(context.Context, *Command) (*Response, error)
	SetSellAmount(context.Context, *Command) (*Response, error)
	SetBuyTrigger(context.Context, *Command) (*Response, error)
	SetSellTrigger(context.Context, *Command) (*Response, error)
	CancelSetSell(context.Context, *Command) (*Response, error)
	CancelSetBuy(context.Context, *Command) (*Response, error)
	DumpLog(context.Context, *Command) (*Response, error)
	DisplaySummary(context.Context, *Command) (*Response, error)
}

func RegisterDayTraderServer(s *grpc.Server, srv DayTraderServer) {
	s.RegisterService(&_DayTrader_serviceDesc, srv)
}

func _DayTrader_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.DayTrader/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).Add(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_Quote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).Quote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.DayTrader/Quote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).Quote(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_Buy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).Buy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.DayTrader/Buy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).Buy(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_Sell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).Sell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.DayTrader/Sell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).Sell(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_CommitBuy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).CommitBuy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.DayTrader/CommitBuy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).CommitBuy(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_CommitSell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).CommitSell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.DayTrader/CommitSell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).CommitSell(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_CancelBuy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).CancelBuy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.DayTrader/CancelBuy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).CancelBuy(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_CancelSell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).CancelSell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.DayTrader/CancelSell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).CancelSell(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_SetBuyAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).SetBuyAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.DayTrader/SetBuyAmount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).SetBuyAmount(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_SetSellAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).SetSellAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.DayTrader/SetSellAmount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).SetSellAmount(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_SetBuyTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).SetBuyTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.DayTrader/SetBuyTrigger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).SetBuyTrigger(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_SetSellTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).SetSellTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.DayTrader/SetSellTrigger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).SetSellTrigger(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_CancelSetSell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).CancelSetSell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.DayTrader/CancelSetSell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).CancelSetSell(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_CancelSetBuy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).CancelSetBuy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.DayTrader/CancelSetBuy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).CancelSetBuy(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_DumpLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).DumpLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.DayTrader/DumpLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).DumpLog(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _DayTrader_DisplaySummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DayTraderServer).DisplaySummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.DayTrader/DisplaySummary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DayTraderServer).DisplaySummary(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

var _DayTrader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "server.DayTrader",
	HandlerType: (*DayTraderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _DayTrader_Add_Handler,
		},
		{
			MethodName: "Quote",
			Handler:    _DayTrader_Quote_Handler,
		},
		{
			MethodName: "Buy",
			Handler:    _DayTrader_Buy_Handler,
		},
		{
			MethodName: "Sell",
			Handler:    _DayTrader_Sell_Handler,
		},
		{
			MethodName: "CommitBuy",
			Handler:    _DayTrader_CommitBuy_Handler,
		},
		{
			MethodName: "CommitSell",
			Handler:    _DayTrader_CommitSell_Handler,
		},
		{
			MethodName: "CancelBuy",
			Handler:    _DayTrader_CancelBuy_Handler,
		},
		{
			MethodName: "CancelSell",
			Handler:    _DayTrader_CancelSell_Handler,
		},
		{
			MethodName: "SetBuyAmount",
			Handler:    _DayTrader_SetBuyAmount_Handler,
		},
		{
			MethodName: "SetSellAmount",
			Handler:    _DayTrader_SetSellAmount_Handler,
		},
		{
			MethodName: "SetBuyTrigger",
			Handler:    _DayTrader_SetBuyTrigger_Handler,
		},
		{
			MethodName: "SetSellTrigger",
			Handler:    _DayTrader_SetSellTrigger_Handler,
		},
		{
			MethodName: "CancelSetSell",
			Handler:    _DayTrader_CancelSetSell_Handler,
		},
		{
			MethodName: "CancelSetBuy",
			Handler:    _DayTrader_CancelSetBuy_Handler,
		},
		{
			MethodName: "DumpLog",
			Handler:    _DayTrader_DumpLog_Handler,
		},
		{
			MethodName: "DisplaySummary",
			Handler:    _DayTrader_DisplaySummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
